### ISSUE TITLE
Design and rational of framework to use

### ISSUE THREAD

**Issue by hlac** [TheOneRed/McMasterGame#2]
- Share what you discover with your team members by providing comments.

**Comment by 822937603** [comment]
![whatsapp image 2017-02-08 at 10 03 58 am](https://cloud.githubusercontent.com/assets/13968055/22914525/eb12d374-f23e-11e6-82b1-26ba590446ad.jpeg)

**Comment by InstantChaos** [comment]
Brainstorming of how the framework should look.

**Comment by TheOneRed** [comment]
![erd](https://cloud.githubusercontent.com/assets/14281773/22956871/a4e26680-f2f2-11e6-97b8-99b7b8ce3436.jpg)
![mcmaster game - page 1](https://cloud.githubusercontent.com/assets/14281773/22956872/a75f45f4-f2f2-11e6-8394-fe62bb2d979e.png)
ERD of Game. Not complete because we were unsure of some relationships

**Comment by antonybogun** [comment]
Yeah, we still have to think about getting titles for a particular set of badges

**Comment by antonybogun** [comment]
![img_20170217_151440144](https://cloud.githubusercontent.com/assets/20272257/23089590/3d5a2a34-f559-11e6-9981-fdc914f01f5d.jpg)
Latest version of ERD
